### ISSUE TITLE
Good state structure

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/jokoanna#9]
I like that you've lifted up the state that needs to be shared to `App.js`, but left state that doesn't just in the component that needs it (`Lipsync.js`). It keeps things nice and simple

**Comment by RohanSSS** [comment]
Yeah keeps everything nice and organised, the states are all at the highest levels they need to be. And it gives you a clear image of each ones required scope

**Comment by jokosanyang** [comment]
![](https://media.giphy.com/media/4Q1DEuAr7ER64f6ctv/giphy.gif)
